### ISSUE TITLE
Cite me

### ISSUE THREAD

**Issue by mvndaai** [bean5/bean5.github.io#1]
https://gist.github.com/mvndaai/034b59746b0172dd3b56

**Comment by bean5** [comment]
I forgot why I had you make this issue on this repo. Do you remember?

**Comment by mvndaai** [comment]
No, just close it...

**Comment by mvndaai** [comment]
That gist is for color bash output... if you wanted to use it somewhere.

**Comment by bean5** [comment]
Ah, probably wanted to mention it on my blog, which is in this project. Good idea.
